### ISSUE TITLE
run webots,throw an error

### ISSUE THREAD

**Issue by wzpoo** [cyberbotics/webots-docker#10]
![屏幕截图 2021-07-08 222718](https://user-images.githubusercontent.com/87136343/124939490-b9cf6080-e03b-11eb-9b1b-9d74c96fdc74.png)
run docker ,then run command in /bin/bash : webots
throw an error: qt error.
Also I run the Dockfile command in Dock image 'ros melodic ubuntu18.04' , it also throw the same error. How to solve this error?

**Comment by wzpoo** [comment]
how to deal with this problem?

**Comment by omichel** [comment]
Can you provide more information on your system? Which Linux version are you using? Are you running it in a virtual environment or on metal? Do you have a NVIDIA graphics cards with proprietary drivers installed?
