### ISSUE TITLE
Use of a smaller base image

### ISSUE THREAD

**Issue by omichel** [cyberbotics/webots-docker#17]
I am wondering whether we should use a smaller base image for our docker as we don't need CUDA and we don't need the devel version since we embed a pre-compiled webots distribution.

[nvidia/cudagl:11.4.2-devel-ubuntu20.04](https://hub.docker.com/r/nvidia/cudagl/tags?page=1&name=11.4.2-devel-ubuntu20):
- weights 2.95 GB
- contains CUDA

[nvidia/opengl:1.2-glvnd-runtime-ubuntu20.04](https://hub.docker.com/r/nvidia/opengl/tags?page=1&name=1.2-glvnd-runtime-ubuntu20.04):
- weights 123 MB (about 24 times lighter!)

That would make the resulting image significantly lighter.

**Note 1**: In some rare cases, CUDA might be needed if some controllers use hardware accelerated machine learning libraries such as pytorch. However, in such cases, it would be better run Webots inside its own docker and the controllers in their own CUDA derived dockers.

**Note 2**: I suppose the `-devel-` version (137 MB) contains `gcc`, `make`, etc. which may be needed if we want to be able to recompile controllers. But this shouldn't be needed in case the controllers are running inside their own docker container. Thus the `-runtime-` version may be sufficient in this case. However currently, we often recompile the controller in the webots docker, so the `-devel-` version may be better until we separate the controllers and webots in different dockers.

**Comment by BenjaminDeleze** [comment]
Seems worth testing

**Comment by BenjaminDeleze** [comment]
I will try it
